# Generated by Django 4.1.5 on 2023-03-09 03:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomchat',
            unique_together={('creator', 'companion')},
        ),
    ]
