# Generated by Django 4.1.5 on 2023-02-07 13:23

import Book.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=9192, null=True, verbose_name='Описание')),
                ('author', models.CharField(max_length=1024, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('title', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='StateCategory',
            fields=[
                ('title', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Название состояния')),
            ],
            options={
                'verbose_name': 'Состояние книги',
                'verbose_name_plural': 'Состояния книг',
            },
        ),
        migrations.CreateModel(
            name='PhotoBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('image', models.ImageField(upload_to=Book.models.get_name_image, verbose_name='Образ')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Фото книги',
                'verbose_name_plural': 'Фото книг',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Book.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='book',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Book.statecategory', verbose_name='Состояние книги'),
        ),
    ]
